### ISSUE TITLE
Enums support

### ISSUE THREAD

**Issue by Bo98** [JohnnyCrazy/glua-scrapper#2]
It currently misses enumerations. It'd be quite handy if enums were handled too.

**Comment by JohnnyCrazy** [comment]
I left it out because of the high amount of ENUMs. (The size of the ACT enum is enormous)
I guess we can try, but I have the feeling performance will suffer in our autocomple-projects.

**Comment by JohnnyCrazy** [comment]
This won't come anytime near due to too large enums
